name: konfig-toml-parser CI/CD Workflow

on:
  push:
    branhces: [master]
  pull_request:
    branhces: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
